//! # Episodic memory
//!
//! LanceDB-backed vector store for distilled memories. Stores events with
//! embeddings generated by fastembed (BGESmallENV15Q, 384 dimensions).
//!
//! Episodic memory is retrieved via semantic similarity when the orchestrator
//! wakes up. Each entry represents a "thing worth remembering" — a summarized
//! moment from the user's day.
//!
//! No automatic deletion — users manage retention via the dashboard.

use anyhow::{Context, Result};
use arrow_array::types::Float32Type;
use arrow_array::{
    Array, Float32Array, FixedSizeListArray, RecordBatch, StringArray,
};
use arrow_schema::{DataType, Field, Schema};
use chrono::{DateTime, Utc};
use lancedb::query::{ExecutableQuery, QueryBase};
use lancedb::{connect, Connection, Table};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tracing::{debug, info, warn};

/// Embedding dimension for BGESmallENV15Q model.
pub const EMBEDDING_DIM: usize = 384;

/// Table name in LanceDB.
const TABLE_NAME: &str = "episodic_events";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// The kind of episodic event stored in memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EventKind {
    /// A distilled memory from the raw log.
    Remember,
    /// An orchestrator wake-up occurred.
    Wake,
    /// A user message was processed.
    UserMessage,
    /// Kairo produced a response.
    KairoResponse,
}

impl EventKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Remember => "remember",
            Self::Wake => "wake",
            Self::UserMessage => "user_message",
            Self::KairoResponse => "kairo_response",
        }
    }

    pub fn from_str_lossy(s: &str) -> Self {
        match s {
            "remember" => Self::Remember,
            "wake" => Self::Wake,
            "user_message" => Self::UserMessage,
            "kairo_response" => Self::KairoResponse,
            _ => Self::Remember,
        }
    }
}

/// A single episodic memory entry.
///
/// Stored in LanceDB with a vector embedding for similarity search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EpisodicEvent {
    /// Unique identifier.
    pub id: String,
    /// When this event occurred.
    pub ts: DateTime<Utc>,
    /// What kind of event this is.
    pub kind: EventKind,
    /// Natural language summary of the event.
    pub summary: String,
    /// Importance score (0.0 to 1.0).
    pub importance: f32,
    /// Tags for categorization (e.g. ["debugging", "kairo", "triage"]).
    pub tags: Vec<String>,
    /// The perception frame that triggered this event (if applicable).
    pub source_frame_id: Option<String>,
}

/// A search result from episodic memory, including the similarity score.
#[derive(Debug, Clone)]
pub struct EpisodicSearchResult {
    pub event: EpisodicEvent,
    /// Distance from the query vector (lower = more similar for L2,
    /// but LanceDB returns _distance so we expose it directly).
    pub distance: f32,
}

// ---------------------------------------------------------------------------
// Embedding model wrapper
// ---------------------------------------------------------------------------

/// Wraps fastembed for generating text embeddings.
///
/// Uses BGESmallENV15Q (66 MB, 384 dimensions) by default.
pub struct Embedder {
    model: fastembed::TextEmbedding,
}

impl Embedder {
    /// Loads the embedding model. First call downloads the model if needed.
    pub fn new() -> Result<Self> {
        use fastembed::TextEmbedding;

        let options = fastembed::TextInitOptions::new(fastembed::EmbeddingModel::BGESmallENV15Q)
            .with_show_download_progress(true);
        let model = TextEmbedding::try_new(options)
            .context("Failed to load BGESmallENV15Q embedding model")?;

        info!(
            layer = "memory",
            component = "episodic",
            model = "BGESmallENV15Q",
            dim = EMBEDDING_DIM,
            "Embedding model loaded"
        );

        Ok(Self { model })
    }

    /// Generates an embedding for a single text.
    pub fn embed_one(&mut self, text: &str) -> Result<Vec<f32>> {
        let embeddings = self
            .model
            .embed(vec![text.to_string()], None)
            .context("Failed to generate embedding")?;

        embeddings
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("Embedding model returned no results"))
    }

    /// Generates embeddings for multiple texts in a batch.
    pub fn embed_batch(&mut self, texts: &[String]) -> Result<Vec<Vec<f32>>> {
        self.model
            .embed(texts.to_vec(), None)
            .context("Failed to generate batch embeddings")
    }
}

// ---------------------------------------------------------------------------
// Episodic store
// ---------------------------------------------------------------------------

/// Manages the LanceDB episodic memory database.
///
/// Provides insert and vector search operations. The embedding model is loaded
/// on construction and used for both writing (embed the summary) and querying
/// (embed the query text).
pub struct EpisodicStore {
    db: Connection,
    table: Option<Table>,
    embedder: Embedder,
}

impl EpisodicStore {
    /// Opens (or creates) the episodic memory database at the given directory.
    ///
    /// Also initializes the embedding model (first call may download ~66 MB).
    pub async fn open(db_dir: &str) -> Result<Self> {
        // Ensure the directory exists.
        if !db_dir.starts_with("memory://") {
            std::fs::create_dir_all(db_dir).with_context(|| {
                format!("Failed to create LanceDB directory: {db_dir}")
            })?;
        }

        let db = connect(db_dir)
            .execute()
            .await
            .with_context(|| format!("Failed to connect to LanceDB at {db_dir}"))?;

        let embedder = Embedder::new()?;

        let mut store = Self {
            db,
            table: None,
            embedder,
        };

        // Try to open existing table, or leave as None (created on first insert).
        store.table = store.db.open_table(TABLE_NAME).execute().await.ok();

        if store.table.is_some() {
            info!(
                layer = "memory",
                component = "episodic",
                "Opened existing episodic memory table"
            );
        } else {
            debug!(
                layer = "memory",
                component = "episodic",
                "No existing episodic table — will create on first insert"
            );
        }

        Ok(store)
    }

    /// Returns the Arrow schema for the episodic events table.
    fn table_schema() -> Arc<Schema> {
        Arc::new(Schema::new(vec![
            Field::new("id", DataType::Utf8, false),
            Field::new("ts", DataType::Utf8, false),
            Field::new("kind", DataType::Utf8, false),
            Field::new("summary", DataType::Utf8, false),
            Field::new("importance", DataType::Float32, false),
            Field::new("tags", DataType::Utf8, false), // JSON array as string
            Field::new("source_frame_id", DataType::Utf8, true),
            Field::new(
                "vector",
                DataType::FixedSizeList(
                    Arc::new(Field::new("item", DataType::Float32, true)),
                    EMBEDDING_DIM as i32,
                ),
                true,
            ),
        ]))
    }

    /// Creates a RecordBatch from a single event and its embedding.
    fn event_to_batch(event: &EpisodicEvent, embedding: &[f32]) -> Result<RecordBatch> {
        let schema = Self::table_schema();

        let id_arr = StringArray::from(vec![event.id.as_str()]);
        let ts_arr = StringArray::from(vec![event.ts.to_rfc3339()]);
        let kind_arr = StringArray::from(vec![event.kind.as_str()]);
        let summary_arr = StringArray::from(vec![event.summary.as_str()]);
        let importance_arr = Float32Array::from(vec![event.importance]);
        let tags_json = serde_json::to_string(&event.tags).unwrap_or_else(|_| "[]".to_string());
        let tags_arr = StringArray::from(vec![tags_json.as_str()]);
        let frame_id_arr = StringArray::from(vec![event.source_frame_id.as_deref()]);

        // Build the fixed-size list for the vector column using from_iter_primitive.
        // Wraps the embedding as a single row with EMBEDDING_DIM elements.
        let vector_arr = FixedSizeListArray::from_iter_primitive::<Float32Type, _, _>(
            vec![Some(embedding.iter().map(|&v| Some(v)))],
            EMBEDDING_DIM as i32,
        );

        RecordBatch::try_new(
            schema,
            vec![
                Arc::new(id_arr),
                Arc::new(ts_arr),
                Arc::new(kind_arr),
                Arc::new(summary_arr),
                Arc::new(importance_arr),
                Arc::new(tags_arr),
                Arc::new(frame_id_arr),
                Arc::new(vector_arr),
            ],
        )
        .context("Failed to create RecordBatch")
    }

    /// Inserts an episodic event into the store.
    ///
    /// Generates an embedding from the event's summary text automatically.
    pub async fn insert_event(&mut self, event: &EpisodicEvent) -> Result<()> {
        let embedding = self.embedder.embed_one(&event.summary)?;

        if embedding.len() != EMBEDDING_DIM {
            anyhow::bail!(
                "Embedding dimension mismatch: expected {EMBEDDING_DIM}, got {}",
                embedding.len()
            );
        }

        let batch = Self::event_to_batch(event, &embedding)?;

        match &self.table {
            Some(table) => {
                table
                    .add(vec![batch])
                    .execute()
                    .await
                    .context("Failed to add event to episodic table")?;
            }
            None => {
                // First insert — create the table.
                let table = self
                    .db
                    .create_table(TABLE_NAME, vec![batch])
                    .execute()
                    .await
                    .context("Failed to create episodic table")?;
                self.table = Some(table);
                info!(
                    layer = "memory",
                    component = "episodic",
                    "Created episodic memory table"
                );
            }
        }

        debug!(
            layer = "memory",
            component = "episodic",
            event_id = %event.id,
            kind = event.kind.as_str(),
            "Inserted episodic event"
        );

        Ok(())
    }

    /// Searches for events similar to the query text.
    ///
    /// Returns up to `limit` results, ordered by similarity (most similar first).
    pub async fn search_similar(
        &mut self,
        query_text: &str,
        limit: usize,
    ) -> Result<Vec<EpisodicSearchResult>> {
        let table = match &self.table {
            Some(t) => t,
            None => return Ok(Vec::new()), // No data yet.
        };

        let query_embedding = self.embedder.embed_one(query_text)?;

        let results = table
            .vector_search(query_embedding)
            .context("Failed to build vector search query")?
            .limit(limit)
            .execute()
            .await
            .context("Failed to execute vector search")?;

        let mut events = Vec::new();
        let batches: Vec<RecordBatch> = results
            .try_collect()
            .await
            .context("Failed to collect search results")?;

        for batch in &batches {
            let ids = batch
                .column_by_name("id")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let timestamps = batch
                .column_by_name("ts")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let kinds = batch
                .column_by_name("kind")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let summaries = batch
                .column_by_name("summary")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let importances = batch
                .column_by_name("importance")
                .and_then(|c| c.as_any().downcast_ref::<Float32Array>());
            let tags_col = batch
                .column_by_name("tags")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let frame_ids = batch
                .column_by_name("source_frame_id")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let distances = batch
                .column_by_name("_distance")
                .and_then(|c| c.as_any().downcast_ref::<Float32Array>());

            let (Some(ids), Some(timestamps), Some(kinds), Some(summaries), Some(importances)) =
                (ids, timestamps, kinds, summaries, importances)
            else {
                warn!(
                    layer = "memory",
                    component = "episodic",
                    "Search result batch missing expected columns"
                );
                continue;
            };

            for i in 0..batch.num_rows() {
                let ts_str = timestamps.value(i);
                let ts = DateTime::parse_from_rfc3339(ts_str)
                    .map(|dt| dt.with_timezone(&Utc))
                    .unwrap_or_else(|_| Utc::now());

                let tags: Vec<String> = tags_col
                    .and_then(|t| serde_json::from_str(t.value(i)).ok())
                    .unwrap_or_default();

                let source_frame_id = frame_ids
                    .and_then(|f| {
                        if f.is_null(i) {
                            None
                        } else {
                            Some(f.value(i).to_string())
                        }
                    });

                let distance = distances.map(|d| d.value(i)).unwrap_or(0.0);

                events.push(EpisodicSearchResult {
                    event: EpisodicEvent {
                        id: ids.value(i).to_string(),
                        ts,
                        kind: EventKind::from_str_lossy(kinds.value(i)),
                        summary: summaries.value(i).to_string(),
                        importance: importances.value(i),
                        tags,
                        source_frame_id,
                    },
                    distance,
                });
            }
        }

        Ok(events)
    }

    /// Returns the N most recent events, ordered by timestamp descending.
    pub async fn recent_events(&self, limit: usize) -> Result<Vec<EpisodicEvent>> {
        let table = match &self.table {
            Some(t) => t,
            None => return Ok(Vec::new()),
        };

        let results = table
            .query()
            .limit(limit)
            .execute()
            .await
            .context("Failed to query recent events")?;

        let batches: Vec<RecordBatch> = results
            .try_collect()
            .await
            .context("Failed to collect recent events")?;

        let mut events = Vec::new();
        for batch in &batches {
            let ids = batch
                .column_by_name("id")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let timestamps = batch
                .column_by_name("ts")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let kinds = batch
                .column_by_name("kind")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let summaries = batch
                .column_by_name("summary")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let importances = batch
                .column_by_name("importance")
                .and_then(|c| c.as_any().downcast_ref::<Float32Array>());
            let tags_col = batch
                .column_by_name("tags")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());
            let frame_ids = batch
                .column_by_name("source_frame_id")
                .and_then(|c| c.as_any().downcast_ref::<StringArray>());

            let (Some(ids), Some(timestamps), Some(kinds), Some(summaries), Some(importances)) =
                (ids, timestamps, kinds, summaries, importances)
            else {
                continue;
            };

            for i in 0..batch.num_rows() {
                let ts_str = timestamps.value(i);
                let ts = DateTime::parse_from_rfc3339(ts_str)
                    .map(|dt| dt.with_timezone(&Utc))
                    .unwrap_or_else(|_| Utc::now());

                let tags: Vec<String> = tags_col
                    .and_then(|t| serde_json::from_str(t.value(i)).ok())
                    .unwrap_or_default();

                let source_frame_id = frame_ids
                    .and_then(|f| {
                        if f.is_null(i) {
                            None
                        } else {
                            Some(f.value(i).to_string())
                        }
                    });

                events.push(EpisodicEvent {
                    id: ids.value(i).to_string(),
                    ts,
                    kind: EventKind::from_str_lossy(kinds.value(i)),
                    summary: summaries.value(i).to_string(),
                    importance: importances.value(i),
                    tags,
                    source_frame_id,
                });
            }
        }

        // Sort by timestamp descending (LanceDB doesn't guarantee order without explicit sort).
        events.sort_by(|a, b| b.ts.cmp(&a.ts));
        events.truncate(limit);

        Ok(events)
    }

    /// Returns the total number of events in the store.
    pub async fn event_count(&self) -> Result<usize> {
        let table = match &self.table {
            Some(t) => t,
            None => return Ok(0),
        };

        let count = table
            .count_rows(None)
            .await
            .context("Failed to count episodic events")?;

        Ok(count)
    }
}

// We need this import for try_collect on the stream.
use futures::TryStreamExt;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_event(summary: &str, kind: EventKind) -> EpisodicEvent {
        EpisodicEvent {
            id: uuid::Uuid::new_v4().to_string(),
            ts: Utc::now(),
            kind,
            summary: summary.to_string(),
            importance: 0.7,
            tags: vec!["test".to_string()],
            source_frame_id: None,
        }
    }

    #[tokio::test]
    async fn test_embedder_produces_correct_dimension() {
        let mut embedder = Embedder::new().unwrap();
        let embedding = embedder.embed_one("test text").unwrap();
        assert_eq!(embedding.len(), EMBEDDING_DIM);
    }

    #[tokio::test]
    async fn test_insert_and_count() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open(db_path).await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 0);

        let event = make_event("User was debugging triage layer", EventKind::Remember);
        store.insert_event(&event).await.unwrap();

        assert_eq!(store.event_count().await.unwrap(), 1);
    }

    #[tokio::test]
    async fn test_insert_and_search() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open(db_path).await.unwrap();

        // Insert some events.
        store
            .insert_event(&make_event(
                "User was debugging the triage JSON parsing logic",
                EventKind::Remember,
            ))
            .await
            .unwrap();
        store
            .insert_event(&make_event(
                "User mentioned a meeting with Jan at 14:00",
                EventKind::Remember,
            ))
            .await
            .unwrap();
        store
            .insert_event(&make_event(
                "Kairo responded about the cargo build error",
                EventKind::KairoResponse,
            ))
            .await
            .unwrap();

        // Search for something related to debugging.
        let results = store
            .search_similar("triage debugging error", 2)
            .await
            .unwrap();

        assert!(!results.is_empty());
        assert!(results.len() <= 2);

        // The debugging-related event should be most similar.
        let top = &results[0];
        assert!(
            top.event.summary.contains("triage") || top.event.summary.contains("error"),
            "Expected debugging-related result, got: {}",
            top.event.summary
        );
    }

    #[tokio::test]
    async fn test_recent_events() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open(db_path).await.unwrap();

        for i in 0..5 {
            let mut event = make_event(&format!("Event number {i}"), EventKind::Remember);
            event.ts = Utc::now() + chrono::Duration::seconds(i as i64);
            store.insert_event(&event).await.unwrap();
        }

        let recent = store.recent_events(3).await.unwrap();
        assert_eq!(recent.len(), 3);

        // Should be in reverse chronological order.
        assert!(recent[0].ts >= recent[1].ts);
        assert!(recent[1].ts >= recent[2].ts);
    }

    #[tokio::test]
    async fn test_empty_store_search_returns_empty() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open(db_path).await.unwrap();
        let results = store.search_similar("anything", 5).await.unwrap();
        assert!(results.is_empty());
    }
}
