//! # Episodic memory
//!
//! LanceDB-backed vector store for distilled memories. Stores events with
//! embeddings generated by fastembed (BGESmallENV15Q, 384 dimensions).
//!
//! Episodic memory is retrieved via semantic similarity when the orchestrator
//! wakes up. Each entry represents a "thing worth remembering" — a summarized
//! moment from the user's day.
//!
//! No automatic deletion — users manage retention via the dashboard.

use anyhow::{Context, Result};
use arrow_array::types::Float32Type;
use arrow_array::{Array, FixedSizeListArray, Float32Array, RecordBatch, StringArray};
use arrow_schema::{DataType, Field, Schema};
use chrono::{DateTime, Utc};
use lancedb::query::{ExecutableQuery, QueryBase};
use lancedb::table::NewColumnTransform;
use lancedb::{connect, Connection, Table};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tracing::{debug, info, warn};

use crate::config::{continuum_data_dir, continuum_dev_dir, env_or_legacy};
use crate::memory::events::{event_enum_token, parse_event_enum, EventSensitivity};

/// Embedding dimension for BGESmallENV15Q model.
pub const EMBEDDING_DIM: usize = 384;

/// Table name in LanceDB.
const TABLE_NAME: &str = "episodic_events";

/// The additive column introduced by Task B6 (spec §4.11).
const PROJECT_COLUMN: &str = "project";

/// The additive column introduced by fixwave 3a (C1): the §4.1 zone
/// sensitivity of the source event, carried so the cloud egress gate can
/// see it on a *distilled* memory and not only on the raw event.
const SENSITIVITY_COLUMN: &str = "sensitivity";

/// Additive columns, in the order a freshly created table gets them.
/// Every one of these is migrated onto an older table by
/// [`EpisodicStore::migrate_additive_columns`].
const ADDITIVE_COLUMNS: [&str; 2] = [PROJECT_COLUMN, SENSITIVITY_COLUMN];

/// The column layout a freshly created episodic table gets, in order.
fn canonical_column_names() -> Vec<String> {
    [
        "id",
        "ts",
        "kind",
        "summary",
        "importance",
        "tags",
        "source_frame_id",
        PROJECT_COLUMN,
        SENSITIVITY_COLUMN,
        "vector",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}

/// How many rows to over-fetch per requested result when a project
/// filter is active (the filter runs after the vector search).
const FILTER_OVERFETCH: usize = 4;

/// Floor for the over-fetch, so a `limit: 1` query still has something to
/// filter over.
const FILTER_OVERFETCH_MIN: usize = 20;

/// The soft project filter (Task B6, spec §4.11): no filter passes
/// everything, and an unattributed memory (`None`) passes every filter —
/// only a memory belonging to a *different* project is dropped.
fn project_matches(filter: Option<&str>, event_project: Option<&str>) -> bool {
    match (filter, event_project) {
        (None, _) => true,
        (Some(_), None) => true,
        (Some(want), Some(have)) => want == have,
    }
}

/// Decodes one Arrow batch into episodic events, or `None` when a
/// required column is missing (a corrupt/foreign table — never invent
/// values). `project` is optional on purpose: tables written before Task
/// B6 have no such column and read as unattributed.
fn events_from_batch(batch: &RecordBatch) -> Option<Vec<EpisodicEvent>> {
    let string_col = |name: &str| {
        batch
            .column_by_name(name)
            .and_then(|c| c.as_any().downcast_ref::<StringArray>())
    };
    let ids = string_col("id")?;
    let timestamps = string_col("ts")?;
    let kinds = string_col("kind")?;
    let summaries = string_col("summary")?;
    let importances = batch
        .column_by_name("importance")
        .and_then(|c| c.as_any().downcast_ref::<Float32Array>())?;
    let tags_col = string_col("tags");
    let frame_ids = string_col("source_frame_id");
    let projects = string_col(PROJECT_COLUMN);
    let sensitivities = string_col(SENSITIVITY_COLUMN);

    let nullable_at = |col: Option<&StringArray>, i: usize| {
        col.and_then(|c| {
            if c.is_null(i) {
                None
            } else {
                Some(c.value(i).to_string())
            }
        })
    };

    let mut events = Vec::with_capacity(batch.num_rows());
    for i in 0..batch.num_rows() {
        let ts = DateTime::parse_from_rfc3339(timestamps.value(i))
            .map(|dt| dt.with_timezone(&Utc))
            .unwrap_or_else(|_| Utc::now());
        let tags: Vec<String> = tags_col
            .and_then(|t| serde_json::from_str(t.value(i)).ok())
            .unwrap_or_default();
        events.push(EpisodicEvent {
            id: ids.value(i).to_string(),
            ts,
            kind: EventKind::from_str_lossy(kinds.value(i)),
            summary: summaries.value(i).to_string(),
            importance: importances.value(i),
            tags,
            source_frame_id: nullable_at(frame_ids, i),
            project: nullable_at(projects, i),
            // A row written before the column existed (or by a build whose
            // migration was refused) reads `cloud_allowed`: that is what it
            // was written as, and defaulting the other way would silently
            // hide every pre-existing memory from every cloud-bound render.
            sensitivity: nullable_at(sensitivities, i)
                .and_then(|token| parse_event_enum::<EventSensitivity>(&token))
                .unwrap_or(EventSensitivity::CloudAllowed),
        });
    }
    Some(events)
}

/// The Arrow field definition for one episodic column, or `None` for a
/// name Continuum does not own (a column added by some other tool — read
/// around, never written).
///
/// Single source of truth: both the create-table schema and every written
/// batch are built from this, so a table created by an older build and a
/// batch written by a newer one cannot disagree about types.
fn canonical_field(name: &str) -> Option<Field> {
    Some(match name {
        "id" => Field::new("id", DataType::Utf8, false),
        "ts" => Field::new("ts", DataType::Utf8, false),
        "kind" => Field::new("kind", DataType::Utf8, false),
        "summary" => Field::new("summary", DataType::Utf8, false),
        "importance" => Field::new("importance", DataType::Float32, false),
        // JSON array as string.
        "tags" => Field::new("tags", DataType::Utf8, false),
        "source_frame_id" => Field::new("source_frame_id", DataType::Utf8, true),
        PROJECT_COLUMN => Field::new(PROJECT_COLUMN, DataType::Utf8, true),
        SENSITIVITY_COLUMN => Field::new(SENSITIVITY_COLUMN, DataType::Utf8, true),
        "vector" => Field::new(
            "vector",
            DataType::FixedSizeList(
                Arc::new(Field::new("item", DataType::Float32, true)),
                EMBEDDING_DIM as i32,
            ),
            true,
        ),
        _ => return None,
    })
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// The kind of episodic event stored in memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EventKind {
    /// A distilled memory from the raw log.
    Remember,
    /// An orchestrator wake-up occurred.
    Wake,
    /// A user message was processed.
    UserMessage,
    /// Continuum produced a response.
    ContinuumResponse,
    /// An MCP tool was invoked by the orchestrator (audit trail).
    ToolCall,
}

impl EventKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Remember => "remember",
            Self::Wake => "wake",
            Self::UserMessage => "user_message",
            Self::ContinuumResponse => "continuum_response",
            Self::ToolCall => "tool_call",
        }
    }

    pub fn from_str_lossy(s: &str) -> Self {
        match s {
            "remember" => Self::Remember,
            "wake" => Self::Wake,
            "user_message" => Self::UserMessage,
            "continuum_response" => Self::ContinuumResponse,
            "tool_call" => Self::ToolCall,
            _ => Self::Remember,
        }
    }
}

/// A single episodic memory entry.
///
/// Stored in LanceDB with a vector embedding for similarity search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EpisodicEvent {
    /// Unique identifier.
    pub id: String,
    /// When this event occurred.
    pub ts: DateTime<Utc>,
    /// What kind of event this is.
    pub kind: EventKind,
    /// Natural language summary of the event.
    pub summary: String,
    /// Importance score (0.0 to 1.0).
    pub importance: f32,
    /// Tags for categorization (e.g. ["debugging", "continuum", "triage"]).
    pub tags: Vec<String>,
    /// The perception frame that triggered this event (if applicable).
    pub source_frame_id: Option<String>,
    /// The project this memory belongs to (context engine spec §4.11,
    /// Task B6), taken from the source `context_events` row's resolved
    /// project. `None` for memories with no project attribution — either
    /// because nothing resolved, or because the row predates B6 (legacy
    /// LanceDB tables have no `project` column at all and always read as
    /// `None`; see [`EpisodicStore::open`]'s additive migration).
    ///
    /// Retrieval filters on it *softly*: unattributed memories are never
    /// hidden, only cross-project ones (see
    /// [`EpisodicStore::search_similar`]).
    #[serde(default)]
    pub project: Option<String>,
    /// The §4.1 zone sensitivity inherited from whatever this memory was
    /// distilled from (fixwave 3a, C1).
    ///
    /// A distilled memory is a *summary of the same text* the source event
    /// carried, so it inherits the source's sensitivity — otherwise text
    /// withheld from the cloud as an event would be sent to Anthropic as a
    /// memory one distillation pass later. The wake packager maps it onto
    /// `MemoryLine::local_only`, which the renderer's cloud gate enforces.
    ///
    /// Defaults to [`EventSensitivity::CloudAllowed`]: legacy rows (and
    /// tables whose additive migration was refused) have no column to read,
    /// and hiding every pre-existing memory would be a silent recall
    /// regression.
    #[serde(default = "default_sensitivity")]
    pub sensitivity: EventSensitivity,
}

/// Serde/legacy default for [`EpisodicEvent::sensitivity`].
fn default_sensitivity() -> EventSensitivity {
    EventSensitivity::CloudAllowed
}

/// A search result from episodic memory, including the similarity score.
#[derive(Debug, Clone)]
pub struct EpisodicSearchResult {
    pub event: EpisodicEvent,
    /// Distance from the query vector (lower = more similar for L2,
    /// but LanceDB returns _distance so we expose it directly).
    pub distance: f32,
}

// ---------------------------------------------------------------------------
// Embedding model wrapper
// ---------------------------------------------------------------------------

/// Wraps fastembed for generating text embeddings.
///
/// Uses BGESmallENV15Q (66 MB, 384 dimensions) by default.
pub struct Embedder {
    backend: EmbedderBackend,
}

enum EmbedderBackend {
    Real(Box<fastembed::TextEmbedding>),
    #[cfg(test)]
    Deterministic,
}

impl Embedder {
    /// Loads the embedding model from the Continuum model cache.
    ///
    /// Resolution order for the cache directory:
    /// 1. `CONTINUUM_EMBEDDINGS_CACHE_DIR` — explicit override
    /// 2. `CONTINUUM_MODELS_DIR/embeddings` — unified Continuum model root
    /// 3. `~/.continuum/models/embeddings`
    /// 4. `~/.continuum-dev/models/embeddings` (dev tree)
    ///
    /// If the model is not present on disk, behaviour is controlled by
    /// `CONTINUUM_OFFLINE`:
    ///   - unset / false → download from HuggingFace and log a warning
    ///     (non-negotiable #2 lets us reach Anthropic / ElevenLabs; model
    ///     downloads are not telemetry, but still an explicit network
    ///     egress — so we surface it loudly)
    ///   - set to `1` / `true` → refuse to download, return a hard error
    ///     asking the user to run `scripts/download-models.ps1`
    pub fn new() -> Result<Self> {
        use fastembed::TextEmbedding;

        let cache_dir = resolve_embeddings_cache_dir();
        std::fs::create_dir_all(&cache_dir).with_context(|| {
            format!(
                "Failed to create embeddings cache dir: {}",
                cache_dir.display()
            )
        })?;

        let model_present = embedding_model_is_present(&cache_dir);
        let offline = env_or_legacy("CONTINUUM_OFFLINE", "KAIRO_OFFLINE")
            .map(|v| matches!(v.as_str(), "1" | "true" | "TRUE" | "yes"))
            .unwrap_or(false);

        if !model_present {
            if offline {
                anyhow::bail!(
                    "Embedding model 'BGESmallENV15Q' not found at {cache}. \
                     CONTINUUM_OFFLINE is set, so Continuum will not download it. \
                     Run `scripts/download-models.ps1` (or unset CONTINUUM_OFFLINE) \
                     to pre-stage the model.",
                    cache = cache_dir.display()
                );
            }
            warn!(
                layer = "memory",
                component = "episodic",
                cache_dir = %cache_dir.display(),
                "BGESmallENV15Q not present — downloading from HuggingFace on first use. \
                 Pre-stage via `scripts/download-models.ps1` to avoid this network call."
            );
        }

        let options = fastembed::TextInitOptions::new(fastembed::EmbeddingModel::BGESmallENV15Q)
            .with_cache_dir(cache_dir.clone())
            .with_show_download_progress(!model_present);
        let model = TextEmbedding::try_new(options)
            .context("Failed to load BGESmallENV15Q embedding model")?;

        info!(
            layer = "memory",
            component = "episodic",
            model = "BGESmallENV15Q",
            dim = EMBEDDING_DIM,
            cache_dir = %cache_dir.display(),
            pre_staged = model_present,
            "Embedding model loaded"
        );

        Ok(Self {
            backend: EmbedderBackend::Real(Box::new(model)),
        })
    }

    #[cfg(test)]
    fn deterministic() -> Self {
        Self {
            backend: EmbedderBackend::Deterministic,
        }
    }

    /// Generates an embedding for a single text.
    pub fn embed_one(&mut self, text: &str) -> Result<Vec<f32>> {
        match &mut self.backend {
            EmbedderBackend::Real(model) => model
                .embed(vec![text.to_string()], None)
                .context("Failed to generate embedding")?
                .into_iter()
                .next()
                .ok_or_else(|| anyhow::anyhow!("Embedding model returned no results")),
            #[cfg(test)]
            EmbedderBackend::Deterministic => Ok(deterministic_test_embedding(text)),
        }
    }

    /// Generates embeddings for multiple texts in a batch.
    pub fn embed_batch(&mut self, texts: Vec<String>) -> Result<Vec<Vec<f32>>> {
        match &mut self.backend {
            EmbedderBackend::Real(model) => model
                .embed(texts, None)
                .context("Failed to generate batch embeddings"),
            #[cfg(test)]
            EmbedderBackend::Deterministic => Ok(texts
                .iter()
                .map(|text| deterministic_test_embedding(text))
                .collect()),
        }
    }
}

#[cfg(test)]
fn deterministic_test_embedding(text: &str) -> Vec<f32> {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut embedding = vec![0.0; EMBEDDING_DIM];
    for token in text
        .split(|ch: char| !ch.is_alphanumeric())
        .filter(|token| !token.is_empty())
    {
        let mut hasher = DefaultHasher::new();
        token.to_lowercase().hash(&mut hasher);
        embedding[hasher.finish() as usize % EMBEDDING_DIM] += 1.0;
    }
    let norm = embedding
        .iter()
        .map(|value| value * value)
        .sum::<f32>()
        .sqrt();
    if norm > 0.0 {
        for value in &mut embedding {
            *value /= norm;
        }
    }
    embedding
}

/// Resolve where the embedding model cache lives on disk. See [`Embedder::new`]
/// for the full resolution order.
fn resolve_embeddings_cache_dir() -> std::path::PathBuf {
    if let Some(v) = env_or_legacy(
        "CONTINUUM_EMBEDDINGS_CACHE_DIR",
        "KAIRO_EMBEDDINGS_CACHE_DIR",
    ) {
        return std::path::PathBuf::from(v);
    }
    if let Some(models) = env_or_legacy("CONTINUUM_MODELS_DIR", "KAIRO_MODELS_DIR") {
        return std::path::PathBuf::from(models).join("embeddings");
    }
    let prod = continuum_data_dir().join("models").join("embeddings");
    if prod.exists() {
        return prod;
    }
    continuum_dev_dir().join("models").join("embeddings")
}

/// Heuristic check for whether fastembed has already unpacked BGESmallENV15Q
/// into the given cache directory. fastembed's on-disk layout is a
/// `models--<org>--<name>/snapshots/<hash>/model.onnx` tree under the cache
/// dir; any `model.onnx` under a `BGE`-flavoured directory counts.
fn embedding_model_is_present(cache_dir: &std::path::Path) -> bool {
    let Ok(entries) = std::fs::read_dir(cache_dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_lowercase();
        if !(name.contains("bge") || name.contains("embeddings")) {
            continue;
        }
        if has_onnx(&entry.path(), 4) {
            return true;
        }
    }
    false
}

fn has_onnx(dir: &std::path::Path, depth: usize) -> bool {
    if depth == 0 {
        return false;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() {
            if path
                .extension()
                .and_then(|e| e.to_str())
                .map(|s| s.eq_ignore_ascii_case("onnx"))
                .unwrap_or(false)
            {
                return true;
            }
        } else if path.is_dir() && has_onnx(&path, depth - 1) {
            return true;
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Episodic store
// ---------------------------------------------------------------------------

/// Manages the LanceDB episodic memory database.
///
/// Provides insert and vector search operations. The embedding model is loaded
/// on construction and used for both writing (embed the summary) and querying
/// (embed the query text).
pub struct EpisodicStore {
    db: Connection,
    table: Option<Table>,
    embedder: Embedder,
    /// Column names of the open table, in the table's own order.
    ///
    /// Written rows must match the table's physical layout, and a table
    /// created before Task B6 has `project` appended at the *end* by
    /// [`Self::migrate_project_column`] rather than in the canonical
    /// position — so batches are built against this list, not blindly
    /// against [`Self::table_schema`]. It is also the graceful-degradation
    /// path: if the migration fails, `project` is simply absent here and
    /// inserts keep working without it.
    columns: Vec<String>,
}

impl EpisodicStore {
    /// Opens (or creates) the episodic memory database at the given directory.
    ///
    /// Also initializes the embedding model (first call may download ~66 MB).
    pub async fn open(db_dir: &str) -> Result<Self> {
        // fastembed performs synchronous model discovery/download and ONNX
        // initialization. Running it on an async worker can starve unrelated
        // MCP requests when the runtime has only one or two worker threads.
        let embedder = tokio::task::spawn_blocking(Embedder::new)
            .await
            .context("Embedding model initialization task failed")??;
        Self::open_with_embedder(db_dir, embedder).await
    }

    async fn open_with_embedder(db_dir: &str, embedder: Embedder) -> Result<Self> {
        // Ensure the directory exists.
        if !db_dir.starts_with("memory://") {
            std::fs::create_dir_all(db_dir)
                .with_context(|| format!("Failed to create LanceDB directory: {db_dir}"))?;
        }

        let db = connect(db_dir)
            .execute()
            .await
            .with_context(|| format!("Failed to connect to LanceDB at {db_dir}"))?;

        let mut store = Self {
            db,
            table: None,
            embedder,
            columns: canonical_column_names(),
        };

        // Try to open existing table, or leave as None (created on first insert).
        store.table = store.db.open_table(TABLE_NAME).execute().await.ok();

        if store.table.is_some() {
            store.migrate_additive_columns().await;
            info!(
                layer = "memory",
                component = "episodic",
                columns = store.columns.join(","),
                "Opened existing episodic memory table"
            );
        } else {
            debug!(
                layer = "memory",
                component = "episodic",
                "No existing episodic table — will create on first insert"
            );
        }

        Ok(store)
    }

    /// Test-only constructor using a deterministic hash-based embedder (no
    /// model download, no network). `pub(crate)` rather than private so
    /// sibling test modules (e.g. `memory::distill`'s tests, which need a
    /// real `EpisodicStore` to exercise `distill_once`) can reuse it instead
    /// of duplicating this setup.
    #[cfg(test)]
    pub(crate) async fn open_for_test(db_dir: &str) -> Result<Self> {
        Self::open_with_embedder(db_dir, Embedder::deterministic()).await
    }

    /// Returns the canonical Arrow schema for the episodic events table —
    /// the layout a *freshly created* table gets. Tables created before
    /// Task B6 differ (no `project`, or `project` appended last after
    /// migration); write paths go through [`Self::columns`].
    fn table_schema() -> Arc<Schema> {
        Arc::new(Schema::new(
            canonical_column_names()
                .iter()
                .map(|name| canonical_field(name).expect("canonical name has a canonical field"))
                .collect::<Vec<_>>(),
        ))
    }

    /// Additive LanceDB schema migration for [`ADDITIVE_COLUMNS`]
    /// (`project` — Task B6, spec §4.11; `sensitivity` — fixwave 3a C1):
    /// an existing table that predates a column gets it added, all-null,
    /// in place. Also refreshes [`Self::columns`] from whatever the table
    /// actually has afterwards.
    ///
    /// Never fails the open. If `add_columns` is refused (older Lance
    /// format, read-only directory, concurrent writer), the store simply
    /// keeps writing the columns the table does have: old memories stay
    /// readable, new ones just carry no project / no sensitivity (which
    /// reads back as `cloud_allowed`, i.e. exactly today's behaviour).
    /// Losing an attribute is much cheaper than refusing to open episodic
    /// memory at all.
    async fn migrate_additive_columns(&mut self) {
        let Some(table) = &self.table else {
            self.columns = canonical_column_names();
            return;
        };

        let existing = match table.schema().await {
            Ok(schema) => schema,
            Err(error) => {
                warn!(
                    layer = "memory",
                    component = "episodic",
                    error = %error,
                    "Could not read episodic table schema; assuming the canonical layout"
                );
                self.columns = canonical_column_names();
                return;
            }
        };

        let mut missing = Vec::new();
        for column in ADDITIVE_COLUMNS {
            if existing.field_with_name(column).is_err() {
                missing.push(column);
            }
        }
        for column in &missing {
            let added = Arc::new(Schema::new(vec![
                canonical_field(column).expect("additive column has a canonical field")
            ]));
            match table
                .add_columns(NewColumnTransform::AllNulls(added), None)
                .await
            {
                Ok(_) => info!(
                    layer = "memory",
                    component = "episodic",
                    column = column,
                    "Migrated episodic table: added additive column (all null)"
                ),
                Err(error) => warn!(
                    layer = "memory",
                    component = "episodic",
                    column = column,
                    error = %error,
                    "Could not add the column to the existing episodic table; \
                     continuing without that attribute on new memories"
                ),
            }
        }

        self.columns = match table.schema().await {
            Ok(schema) => schema
                .fields()
                .iter()
                .map(|f| f.name().clone())
                .filter(|name| canonical_field(name).is_some())
                .collect(),
            // Schema unreadable after the attempt: assume the columns that
            // were already there survived and the ones we tried to add did
            // not, so writes stay compatible with the pre-migration table.
            Err(_) => canonical_column_names()
                .into_iter()
                .filter(|name| !missing.iter().any(|m| m == name))
                .collect(),
        };
    }

    /// Creates a RecordBatch from a single event and its embedding,
    /// laid out to match `columns` (the open table's own column order).
    fn event_to_batch(
        event: &EpisodicEvent,
        embedding: &[f32],
        columns: &[String],
    ) -> Result<RecordBatch> {
        let mut fields = Vec::with_capacity(columns.len());
        let mut arrays: Vec<Arc<dyn Array>> = Vec::with_capacity(columns.len());

        for name in columns {
            let field = canonical_field(name)
                .with_context(|| format!("Unknown episodic column in table layout: {name}"))?;
            let array: Arc<dyn Array> = match name.as_str() {
                "id" => Arc::new(StringArray::from(vec![event.id.as_str()])),
                "ts" => Arc::new(StringArray::from(vec![event.ts.to_rfc3339()])),
                "kind" => Arc::new(StringArray::from(vec![event.kind.as_str()])),
                "summary" => Arc::new(StringArray::from(vec![event.summary.as_str()])),
                "importance" => Arc::new(Float32Array::from(vec![event.importance])),
                "tags" => {
                    let tags_json =
                        serde_json::to_string(&event.tags).unwrap_or_else(|_| "[]".to_string());
                    Arc::new(StringArray::from(vec![tags_json]))
                }
                "source_frame_id" => {
                    Arc::new(StringArray::from(vec![event.source_frame_id.as_deref()]))
                }
                PROJECT_COLUMN => Arc::new(StringArray::from(vec![event.project.as_deref()])),
                SENSITIVITY_COLUMN => Arc::new(StringArray::from(vec![event_enum_token(
                    &event.sensitivity,
                )])),
                // Build the fixed-size list for the vector column using
                // from_iter_primitive: one row of EMBEDDING_DIM elements.
                "vector" => Arc::new(
                    FixedSizeListArray::from_iter_primitive::<Float32Type, _, _>(
                        vec![Some(embedding.iter().map(|&v| Some(v)))],
                        EMBEDDING_DIM as i32,
                    ),
                ),
                other => anyhow::bail!("Unhandled episodic column: {other}"),
            };
            fields.push(field);
            arrays.push(array);
        }

        RecordBatch::try_new(Arc::new(Schema::new(fields)), arrays)
            .context("Failed to create RecordBatch")
    }

    /// Inserts an episodic event into the store.
    ///
    /// Generates an embedding from the event's summary text automatically.
    pub async fn insert_event(&mut self, event: &EpisodicEvent) -> Result<()> {
        let embedding = self.embedder.embed_one(&event.summary)?;

        if embedding.len() != EMBEDDING_DIM {
            anyhow::bail!(
                "Embedding dimension mismatch: expected {EMBEDDING_DIM}, got {}",
                embedding.len()
            );
        }

        let batch = Self::event_to_batch(event, &embedding, &self.columns)?;

        match &self.table {
            Some(table) => {
                table
                    .add(vec![batch])
                    .execute()
                    .await
                    .context("Failed to add event to episodic table")?;
            }
            None => {
                // First insert — create the table with the canonical
                // layout (`self.columns` already holds it).
                let table = self
                    .db
                    .create_table(TABLE_NAME, vec![batch])
                    .execute()
                    .await
                    .context("Failed to create episodic table")?;
                self.table = Some(table);
                info!(
                    layer = "memory",
                    component = "episodic",
                    "Created episodic memory table"
                );
            }
        }

        debug!(
            layer = "memory",
            component = "episodic",
            event_id = %event.id,
            kind = event.kind.as_str(),
            "Inserted episodic event"
        );

        Ok(())
    }

    /// Searches for events similar to the query text.
    ///
    /// Returns up to `limit` results, ordered by similarity (most similar first).
    ///
    /// `project` is the optional project filter (Task B6, spec §4.11).
    /// Two deliberate properties:
    ///
    /// - **Soft.** A memory with no project (`None`) always survives the
    ///   filter. Every memory written before B6 is unattributed, and so is
    ///   anything observed while no project resolved — hard-filtering
    ///   would silently empty episodic recall on existing installs.
    ///   Only memories belonging to a *different* project are dropped.
    /// - **Post-search, not pushed down.** Lance predicate pushdown over a
    ///   column that legacy tables may not have is a footgun (the
    ///   migration is best-effort), so the filter runs in Rust over an
    ///   over-fetched result set — `limit * OVERFETCH` rows, floored at
    ///   [`FILTER_OVERFETCH_MIN`], then truncated back to `limit`. The
    ///   cost is one wider vector scan; the benefit is that a table
    ///   without the column behaves exactly like one where every row is
    ///   unattributed.
    pub async fn search_similar(
        &mut self,
        query_text: &str,
        limit: usize,
        project: Option<&str>,
    ) -> Result<Vec<EpisodicSearchResult>> {
        let table = match &self.table {
            Some(t) => t,
            None => return Ok(Vec::new()), // No data yet.
        };

        let query_embedding = self.embedder.embed_one(query_text)?;

        let fetch = match project {
            Some(_) => (limit.saturating_mul(FILTER_OVERFETCH)).max(FILTER_OVERFETCH_MIN),
            None => limit,
        };

        let results = table
            .vector_search(query_embedding)
            .context("Failed to build vector search query")?
            .limit(fetch)
            .execute()
            .await
            .context("Failed to execute vector search")?;

        let mut events = Vec::new();
        let batches: Vec<RecordBatch> = results
            .try_collect()
            .await
            .context("Failed to collect search results")?;

        for batch in &batches {
            let distances = batch
                .column_by_name("_distance")
                .and_then(|c| c.as_any().downcast_ref::<Float32Array>());
            let Some(rows) = events_from_batch(batch) else {
                warn!(
                    layer = "memory",
                    component = "episodic",
                    "Search result batch missing expected columns"
                );
                continue;
            };
            for (i, event) in rows.into_iter().enumerate() {
                if !project_matches(project, event.project.as_deref()) {
                    continue;
                }
                events.push(EpisodicSearchResult {
                    event,
                    distance: distances.map(|d| d.value(i)).unwrap_or(0.0),
                });
            }
        }

        events.truncate(limit);
        Ok(events)
    }

    /// Returns the N most recent events, ordered by timestamp descending.
    pub async fn recent_events(&self, limit: usize) -> Result<Vec<EpisodicEvent>> {
        let table = match &self.table {
            Some(t) => t,
            None => return Ok(Vec::new()),
        };

        let results = table
            .query()
            .limit(limit)
            .execute()
            .await
            .context("Failed to query recent events")?;

        let batches: Vec<RecordBatch> = results
            .try_collect()
            .await
            .context("Failed to collect recent events")?;

        let mut events = Vec::new();
        for batch in &batches {
            let Some(rows) = events_from_batch(batch) else {
                continue;
            };
            events.extend(rows);
        }

        // Sort by timestamp descending (LanceDB doesn't guarantee order without explicit sort).
        events.sort_by(|a, b| b.ts.cmp(&a.ts));
        events.truncate(limit);

        Ok(events)
    }

    /// Wipes every episodic event — the derived-data wipe path
    /// (`curator::run::process_wipe_request`). Drops the underlying LanceDB
    /// table (if one has been created yet) and eagerly recreates it empty
    /// with the same schema [`Self::open`] would lazily create on first
    /// insert, so the store is immediately usable afterward rather than
    /// leaving `self.table` as `None` until the next [`Self::insert_event`]
    /// call (which would make [`Self::event_count`] and
    /// [`Self::search_similar`] both silently answer "0 / empty" in a way
    /// indistinguishable from "table never existed", instead of reflecting
    /// the wipe having actually run).
    pub async fn wipe_all(&mut self) -> Result<()> {
        if self.table.is_some() {
            self.db
                .drop_table(TABLE_NAME, &[])
                .await
                .context("Failed to drop episodic table")?;
            self.table = None;
        }

        let schema = Self::table_schema();
        let table = self
            .db
            .create_empty_table(TABLE_NAME, schema)
            .execute()
            .await
            .context("Failed to recreate episodic table")?;
        self.table = Some(table);
        // The recreated table is canonical, whatever the wiped one was.
        self.columns = canonical_column_names();

        info!(
            layer = "memory",
            component = "episodic",
            "Wiped episodic memory table"
        );

        Ok(())
    }

    /// Deletes every memory derived from the given perception frames — the
    /// episodic rung of the Context page's Forget cascade (spec §4.13).
    ///
    /// Matches on `source_frame_id`, which the distiller writes for
    /// frame-derived and event-derived memories alike (Task B6 keeps it
    /// only when the `raw_reference` parses as a uuid, so a git sha never
    /// masquerades as a frame pointer). Memories with no source frame —
    /// wakes, tool calls, chat turns — are never touched by this call.
    ///
    /// Returns the number of rows deleted. An empty input, or a store with
    /// no table yet, deletes nothing and is not an error.
    pub async fn delete_by_source_frames(&self, frame_ids: &[String]) -> Result<u64> {
        let Some(table) = &self.table else {
            return Ok(0);
        };
        // Frame ids are uuids by construction (they come from
        // `perception_frames.id`), so the only characters that can appear
        // are hex digits and dashes. Anything else is rejected rather than
        // escaped: a predicate is a query language, and this is the one
        // place a caller-supplied string reaches it.
        let quoted: Vec<String> = frame_ids
            .iter()
            .filter(|id| {
                let ok = !id.is_empty()
                    && id.len() <= 64
                    && id.chars().all(|c| c.is_ascii_hexdigit() || c == '-');
                if !ok {
                    warn!(
                        layer = "memory",
                        component = "episodic",
                        source_frame_id = id.as_str(),
                        "Refusing a non-uuid frame id in an episodic delete predicate"
                    );
                }
                ok
            })
            .map(|id| format!("'{id}'"))
            .collect();
        if quoted.is_empty() {
            return Ok(0);
        }
        let predicate = format!("source_frame_id IN ({})", quoted.join(", "));
        let result = table
            .delete(&predicate)
            .await
            .context("Failed to delete episodic events by source frame")?;
        if result.num_deleted_rows > 0 {
            info!(
                layer = "memory",
                component = "episodic",
                deleted = result.num_deleted_rows,
                frames = quoted.len(),
                "Deleted episodic memories derived from forgotten frames"
            );
        }
        Ok(result.num_deleted_rows)
    }

    /// Deletes every memory whose timestamp falls inside `[from, to]` —
    /// the episodic rung of the Context page's delete-range action
    /// (spec §4.13).
    ///
    /// `ts` is stored as an RFC 3339 string (see [`canonical_field`]), and
    /// chrono renders it with a fixed `YYYY-MM-DDTHH:MM:SS[.f]+00:00`
    /// layout, so lexicographic comparison is chronological comparison for
    /// every value this store has ever written.
    pub async fn delete_ts_range(&self, from: DateTime<Utc>, to: DateTime<Utc>) -> Result<u64> {
        let Some(table) = &self.table else {
            return Ok(0);
        };
        if to < from {
            return Ok(0);
        }
        let predicate = format!(
            "ts >= '{}' AND ts <= '{}'",
            from.to_rfc3339(),
            to.to_rfc3339()
        );
        let result = table
            .delete(&predicate)
            .await
            .context("Failed to delete episodic events in range")?;
        if result.num_deleted_rows > 0 {
            info!(
                layer = "memory",
                component = "episodic",
                deleted = result.num_deleted_rows,
                "Purged episodic memories in a user-requested time range"
            );
        }
        Ok(result.num_deleted_rows)
    }

    /// Returns the total number of events in the store.
    pub async fn event_count(&self) -> Result<usize> {
        let table = match &self.table {
            Some(t) => t,
            None => return Ok(0),
        };

        let count = table
            .count_rows(None)
            .await
            .context("Failed to count episodic events")?;

        Ok(count)
    }
}

// We need this import for try_collect on the stream.
use futures::TryStreamExt;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_event(summary: &str, kind: EventKind) -> EpisodicEvent {
        EpisodicEvent {
            id: uuid::Uuid::new_v4().to_string(),
            ts: Utc::now(),
            kind,
            summary: summary.to_string(),
            importance: 0.7,
            tags: vec!["test".to_string()],
            source_frame_id: None,
            project: None,
            sensitivity: EventSensitivity::CloudAllowed,
        }
    }

    #[tokio::test]
    async fn test_embedder_produces_correct_dimension() {
        let mut embedder = Embedder::deterministic();
        let embedding = embedder.embed_one("test text").unwrap();
        assert_eq!(embedding.len(), EMBEDDING_DIM);
    }

    #[tokio::test]
    async fn test_insert_and_count() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 0);

        let event = make_event("User was debugging triage layer", EventKind::Remember);
        store.insert_event(&event).await.unwrap();

        assert_eq!(store.event_count().await.unwrap(), 1);
    }

    #[tokio::test]
    async fn test_insert_and_search() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();

        // Insert some events.
        store
            .insert_event(&make_event(
                "User was debugging the triage JSON parsing logic",
                EventKind::Remember,
            ))
            .await
            .unwrap();
        store
            .insert_event(&make_event(
                "User mentioned a meeting with Jan at 14:00",
                EventKind::Remember,
            ))
            .await
            .unwrap();
        store
            .insert_event(&make_event(
                "Continuum responded about the cargo build error",
                EventKind::ContinuumResponse,
            ))
            .await
            .unwrap();

        // Search for something related to debugging.
        let results = store
            .search_similar("triage debugging error", 2, None)
            .await
            .unwrap();

        assert!(!results.is_empty());
        assert!(results.len() <= 2);

        // The debugging-related event should be most similar.
        let top = &results[0];
        assert!(
            top.event.summary.contains("triage") || top.event.summary.contains("error"),
            "Expected debugging-related result, got: {}",
            top.event.summary
        );
    }

    #[tokio::test]
    async fn test_recent_events() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();

        for i in 0..5 {
            let mut event = make_event(&format!("Event number {i}"), EventKind::Remember);
            event.ts = Utc::now() + chrono::Duration::seconds(i as i64);
            store.insert_event(&event).await.unwrap();
        }

        let recent = store.recent_events(3).await.unwrap();
        assert_eq!(recent.len(), 3);

        // Should be in reverse chronological order.
        assert!(recent[0].ts >= recent[1].ts);
        assert!(recent[1].ts >= recent[2].ts);
    }

    #[tokio::test]
    async fn test_empty_store_search_returns_empty() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();
        let results = store.search_similar("anything", 5, None).await.unwrap();
        assert!(results.is_empty());
    }

    #[tokio::test]
    async fn test_wipe_all_clears_events_and_store_stays_usable() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();
        store
            .insert_event(&make_event("First event", EventKind::Remember))
            .await
            .unwrap();
        store
            .insert_event(&make_event("Second event", EventKind::Wake))
            .await
            .unwrap();
        assert_eq!(store.event_count().await.unwrap(), 2);

        store.wipe_all().await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 0);

        // Store must still be usable after the wipe, not left in a
        // "table missing" state.
        store
            .insert_event(&make_event("Post-wipe event", EventKind::Remember))
            .await
            .unwrap();
        assert_eq!(store.event_count().await.unwrap(), 1);
    }

    // -- Task B6: additive `project` column + soft retrieval filter ----

    /// Creates an `episodic_events` table the way a build *before* Task
    /// B6 would have: every canonical column except `project`.
    async fn create_legacy_table(db_dir: &str, summary: &str) {
        let db = connect(db_dir).execute().await.unwrap();
        let legacy_columns: Vec<String> = canonical_column_names()
            .into_iter()
            .filter(|name| name != PROJECT_COLUMN)
            .collect();
        let event = make_event(summary, EventKind::Remember);
        let embedding = Embedder::deterministic().embed_one(&event.summary).unwrap();
        let batch = EpisodicStore::event_to_batch(&event, &embedding, &legacy_columns).unwrap();
        db.create_table(TABLE_NAME, vec![batch])
            .execute()
            .await
            .unwrap();
    }

    #[tokio::test]
    async fn legacy_table_without_project_opens_reads_and_migrates() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();
        create_legacy_table(db_path, "a memory from before the migration").await;

        // Opening with the B6 code must not fail and must not lose rows.
        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 1);
        let legacy = store.recent_events(10).await.unwrap();
        assert_eq!(legacy.len(), 1);
        assert_eq!(legacy[0].summary, "a memory from before the migration");
        assert_eq!(legacy[0].project, None, "legacy rows read as unattributed");

        // The migration ran, so new inserts carry their project.
        assert!(
            store.columns.iter().any(|c| c == PROJECT_COLUMN),
            "project column should exist after migration, got {:?}",
            store.columns
        );
        let mut fresh = make_event("a memory from after the migration", EventKind::Remember);
        fresh.project = Some("continuum".to_string());
        store.insert_event(&fresh).await.unwrap();

        let all = store.recent_events(10).await.unwrap();
        assert_eq!(all.len(), 2);
        let written = all
            .iter()
            .find(|e| e.summary == "a memory from after the migration")
            .expect("new memory present");
        assert_eq!(written.project.as_deref(), Some("continuum"));
    }

    #[tokio::test]
    async fn legacy_table_reopens_idempotently() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();
        create_legacy_table(db_path, "legacy").await;

        // Migrating twice must be a no-op, not an error or a duplicate
        // column: the runtime reopens the store on every boot.
        let store = EpisodicStore::open_for_test(db_path).await.unwrap();
        drop(store);
        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 1);
        store
            .insert_event(&make_event("after second open", EventKind::Remember))
            .await
            .unwrap();
        assert_eq!(store.event_count().await.unwrap(), 2);
    }

    #[tokio::test]
    async fn search_project_filter_keeps_matching_and_unattributed_memories() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = EpisodicStore::open_for_test(tmp.path().to_str().unwrap())
            .await
            .unwrap();

        for (summary, project) in [
            ("alpha work", Some("alpha")),
            ("beta work", Some("beta")),
            ("unattributed work", None),
        ] {
            let mut event = make_event(summary, EventKind::Remember);
            event.project = project.map(str::to_string);
            store.insert_event(&event).await.unwrap();
        }

        let unfiltered = store.search_similar("work", 10, None).await.unwrap();
        assert_eq!(unfiltered.len(), 3, "no filter returns everything");

        let filtered = store
            .search_similar("work", 10, Some("alpha"))
            .await
            .unwrap();
        let summaries: Vec<&str> = filtered.iter().map(|r| r.event.summary.as_str()).collect();
        assert!(summaries.contains(&"alpha work"));
        assert!(
            summaries.contains(&"unattributed work"),
            "the filter is soft: unattributed memories survive"
        );
        assert!(
            !summaries.contains(&"beta work"),
            "another project's memories are dropped, got {summaries:?}"
        );
    }

    #[tokio::test]
    async fn search_project_filter_still_honours_the_limit() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = EpisodicStore::open_for_test(tmp.path().to_str().unwrap())
            .await
            .unwrap();
        for i in 0..8 {
            let mut event = make_event(&format!("alpha work {i}"), EventKind::Remember);
            event.project = Some("alpha".to_string());
            store.insert_event(&event).await.unwrap();
        }

        let filtered = store
            .search_similar("work", 3, Some("alpha"))
            .await
            .unwrap();
        assert_eq!(filtered.len(), 3, "over-fetch must be truncated to limit");
    }

    #[test]
    fn project_filter_matrix() {
        assert!(project_matches(None, None));
        assert!(project_matches(None, Some("alpha")));
        assert!(project_matches(Some("alpha"), None));
        assert!(project_matches(Some("alpha"), Some("alpha")));
        assert!(!project_matches(Some("alpha"), Some("beta")));
    }

    #[test]
    fn canonical_schema_covers_every_canonical_name() {
        let names = canonical_column_names();
        assert!(names.iter().any(|n| n == PROJECT_COLUMN));
        for name in &names {
            assert!(
                canonical_field(name).is_some(),
                "no field definition for {name}"
            );
        }
        let schema = EpisodicStore::table_schema();
        assert_eq!(schema.fields().len(), names.len());
        for (field, name) in schema.fields().iter().zip(names.iter()) {
            assert_eq!(field.name(), name, "schema order must match column order");
        }
        assert!(canonical_field("not_a_continuum_column").is_none());
    }

    #[tokio::test]
    async fn test_wipe_all_on_never_written_store_is_a_noop() {
        let tmp = tempfile::tempdir().unwrap();
        let db_path = tmp.path().to_str().unwrap();

        let mut store = EpisodicStore::open_for_test(db_path).await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 0);

        store.wipe_all().await.unwrap();
        assert_eq!(store.event_count().await.unwrap(), 0);
    }
}
